### ISSUE TITLE
Feature Request:Adding Audio CAPTCHA and CAPTCHA History in captcha generator 



### ISSUE THREAD

**Issue by vyanky1227** [Sulagna-Dutta-Roy/GGExtensions#217]
Made some changes according to the above topic. please assign this issue @Sulagna-Dutta-Roy ma'am
![Screenshot 2024-05-16 124805](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/132478275/2902e4f4-836f-45b7-b9ed-8d3094fdb540)

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly spare some time to assign. Before raising any pull requests.

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly raise the issue using feature request

**Comment by vyanky1227** [comment]
> Kindly raise the issue using feature request

Already raised issue #217 and also provided solution. Please refer.#217

**Comment by vyanky1227** [comment]
> Kindly spare some time to assign. Before raising any pull requests. 

OK ma'am. This shall be not happen next time. Extremely sorry.

**Comment by Sulagna-Dutta-Roy** [comment]
You can check other people's issues. How the template is provided. 
Kindly do not open blank issues. Also you've opened a new issue, that one I closed because of duplicates. 

Some points to Improve: 

1. Feel free to explore closed Issues. How other people have added as per the guidelines 

2. Also explore closed PRs, if possible. Kindly give me some time to assign all the issues. Because there are no mentors here. 


Thank you for your contributions @vyanky1227

**Comment by vyanky1227** [comment]
Thank you so much ma'am for you support and guidance.
