### ISSUE TITLE
Hangman Game JS Extension

### ISSUE THREAD

**Issue by Nehayp21242929** [Sulagna-Dutta-Roy/GGExtensions#244]
**Is your feature request related to a problem? Please describe.**
 I would like to make a hangman game JS Extension. please assign this task to me.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam, I'd like to work on this issue, if it hasn't been solved yet.
Thank you!

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly check #248 already mentioned.

**Comment by Sulagna-Dutta-Roy** [comment]
@Nehayp21242929 I've to unassigned this. Because I did not receive an update on this PR.

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Mam but the issue #248 is already closed, with reference to this issue. And I wanted to work on this issue, as it hasn't been completed till now.

**Comment by Sulagna-Dutta-Roy** [comment]
Because the scenario is this issue was raised before that time someone also raised the same issue. 
And I closed the other issue for this issue. Now I didn't receive any update on this. 

For now I closed this issue because of no update from the owner. I don't know whether she is working or not. So I closed it. 

Kindly raise issues, I will assign to you 🙏🙏🙏 @Sambit-Mondal

**Comment by Sulagna-Dutta-Roy** [comment]
And I can see you're assigned

**Comment by Sambit-Mondal** [comment]
@Sulagna-Dutta-Roy Ohh!
Okay mam, thank you!
